import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CalendarDays, CheckCircle2, CreditCard, FileText, ShieldCheck } from "lucide-react";

import ClientBillingCheckoutPanel from "@/components/ClientBillingCheckoutPanel";
import { findClientByBillingToken, getClientBillingSummary } from "@/lib/billing/service";
import { BILLING_PLAN_TYPES, BILLING_STATES } from "@/lib/billing/constants";

export const dynamic = "force-dynamic";

function billingTiming(planType) {
  if (planType === BILLING_PLAN_TYPES.STANDARD_WEEKLY) {
    return "The next automatic charge occurs around one week after the first successful payment and continues weekly until cancellation takes effect.";
  }

  return "This onboarding payment is charged once. Any later success fee is requested separately if it becomes payable under your agreement.";
}

function billingButtonLabel(planType, amountLabel) {
  if (planType === BILLING_PLAN_TYPES.STANDARD_WEEKLY) {
    return `Pay ${amountLabel} & Start Weekly Plan`;
  }

  return `Pay ${amountLabel} & Start Onboarding`;
}

export default async function BillingPage({ params }) {
  const { token } = await params;
  const client = await findClientByBillingToken(token);

  if (!client) {
    notFound();
  }

  const billing = getClientBillingSummary(client);
  const isWeekly = billing.planType === BILLING_PLAN_TYPES.STANDARD_WEEKLY;
  const dueTodayLabel = isWeekly ? billing.weeklyAmountLabel : billing.onboardingFeeLabel;
  const recurringLabel = isWeekly ? billing.weeklyAmountLabel : "No weekly recurring charge";
  const disclosure = isWeekly
    ? billing.checkoutDisclosureText
    : "This payment covers the agreed onboarding fee only. Any later success fee is a separate one-time request under the service agreement.";
  const agreementHref = billing.agreementUrl || "/contact";

  return (
    <main className="fj-page" style={{ padding: "72px 0" }}>
      <section className="fj-container" style={{ maxWidth: "980px" }}>
        <div className="fj-pricing-card" style={{ padding: "40px", display: "grid", gap: "28px" }}>
          <div style={{ display: "grid", gap: "12px" }}>
            <span className="fj-announcement" style={{ width: "fit-content" }}>
              <span>Private Billing</span> Secure personalised checkout
            </span>
            <h1 style={{ fontSize: "clamp(2.4rem, 5vw, 4rem)", lineHeight: 1.02 }}>
              {isWeekly ? "Standard Weekly Job Support" : "Two-Month Success-Based Onboarding"}
            </h1>
            <p style={{ maxWidth: "720px", color: "var(--fj-muted)" }}>
              Review your agreed payment terms below. The amount shown here is generated by 9Jobs from your stored commercial terms and cannot be changed in the browser.
            </p>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "16px" }}>
            <div className="fj-pricing-card" style={{ padding: "24px" }}>
              <strong style={{ fontSize: "2.3rem" }}>{dueTodayLabel}</strong>
              <p style={{ marginTop: "8px" }}>Amount due today</p>
            </div>
            <div className="fj-pricing-card" style={{ padding: "24px" }}>
              <strong style={{ fontSize: "2.3rem" }}>{recurringLabel}</strong>
              <p style={{ marginTop: "8px" }}>{isWeekly ? "Charged automatically every week" : "Recurring amount"}</p>
            </div>
          </div>

          <div style={{ display: "grid", gap: "14px" }}>
            {[
              {
                icon: CreditCard,
                title: "Billing timing",
                body: billingTiming(billing.planType),
              },
              {
                icon: ShieldCheck,
                title: "Cancellation rule",
                body: isWeekly
                  ? "You can stop future recurring charges through the supported cancellation path. By default, cancellation takes effect at the end of the current paid weekly period."
                  : "This onboarding payment does not start a weekly recurring subscription.",
              },
              {
                icon: FileText,
                title: "Agreement",
                body: "Review your service agreement and payment terms before completing payment.",
              },
              {
                icon: CalendarDays,
                title: "Current billing status",
                body: billing.billingState === BILLING_STATES.PENDING_AGREEMENT
                  ? "Agreement review is still pending in the system."
                  : `Current status: ${billing.billingState.replaceAll("_", " ")}.`,
              },
            ].map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.title} style={{ display: "flex", gap: "14px", alignItems: "flex-start" }}>
                  <span style={{ width: "42px", height: "42px", borderRadius: "999px", display: "inline-flex", alignItems: "center", justifyContent: "center", background: "rgba(188, 255, 99, 0.18)", color: "#152406" }}>
                    <Icon size={18} />
                  </span>
                  <div style={{ display: "grid", gap: "4px" }}>
                    <strong>{item.title}</strong>
                    <p style={{ margin: 0, color: "var(--fj-muted)" }}>{item.body}</p>
                  </div>
                </div>
              );
            })}
          </div>

          <div style={{ border: "1px solid rgba(17, 24, 39, 0.08)", borderRadius: "22px", padding: "24px", background: "rgba(255,255,255,0.76)" }}>
            <div style={{ display: "flex", alignItems: "flex-start", gap: "12px" }}>
              <CheckCircle2 size={18} style={{ marginTop: "3px", color: "#121a0f" }} />
              <p style={{ margin: 0, fontWeight: 600 }}>
                {disclosure}
              </p>
            </div>
            <div style={{ display: "flex", gap: "12px", flexWrap: "wrap", marginTop: "20px" }}>
              <ClientBillingCheckoutPanel
                token={token}
                planType={billing.planType}
                buttonLabel={billingButtonLabel(billing.planType, dueTodayLabel)}
              />
              <Link href={agreementHref} className="fj-button fj-button--ghost" prefetch={false}>
                Review agreement <ArrowRight size={17} />
              </Link>
            </div>
          </div>

          <p style={{ margin: 0, color: "var(--fj-muted)", fontSize: "0.95rem" }}>
            Need help with billing or cancellation? Email <a href="mailto:info@9jobs.co">info@9jobs.co</a> and include your full name.
          </p>
        </div>
      </section>
    </main>
  );
}
